- name: MongoDB - Add repository
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.2 multiverse'
    filename: 'mongodb3.2'
    state: present
    update_cache: yes

- name: MongoDB - Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes

- name: MongoDB - Running state
  service:
    name: mongod
    state: started
