- name: MongoDB - Install MongoDB and Pip
  apt:
    pkg:
    - mongodb
    - pip
    state: present
    update_cache: yes

- name: MongoDB - Python packages
  pip:
    name:
    - pymongo

- name: MongoDB - Running state
  service:
    name: mongodb
    state: started

- name: MongoDB - Copy mongo.py file
  copy:
    src: mongo.py
    dst: /home/simon/
    owner: simon
    group: simon
    mode: '0700'

- name: MongoDB - Run script mongo.py
  script: /home/simon/mongo.py
  args:
    executable: python 3
