- name: MongoDB - Install MongoDB and Pip
  apt:
    pkg:
    - mongodb
    - python3-pip
    - python-setuptools
    state: present
    update_cache: yes

- name: MongoDB - Install virtualenv python package
  pip:
    name: virtualenv
    executable: /usr/bin/pip3

# - name: MongoDB - Create virtualenv
#   command:
#     cmd: virtualenv "{{ path_file }}/venv"

- name: MongoDB - Python packages
  pip:
    name:
    - pymongo
    # virtualenv: "{{ path_file }}/venv"

- name: MongoDB - Running state
  service:
    name: mongodb
    state: started

# - name: MongoDB - Copy mongo.py file
#   copy:
#     src: mongo.py
#     dest: "{{ path_file }}/"
#     owner: simon
#     group: simon
#     mode: '0700'

- name: MongoDB - Run script mongo.py
  script: 
    free_form: mongo.py"
    # remote_src: yes
  args:
    executable: /usr/bin/python3
