# AWS playbook
---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: my_aws_aws
    region: eu-west-1
    image: ami-035966e8adab4aaad
    sec_group: "{{ id }}-sec"

  tasks:
    - name: "Get instances facts"
      ec2_instance_info:
        region: "{{ region }}"
      register: result

      tags: 'always'


    - name: "Provisioning EC2 instances"
      block:
      - name: "Create security group"
        ec2_group:
          name: "{{ sec_group }}"
          description: "Sec group for app {{ id }}"
          region: "{{ region }}"
          rules:
            - proto: tcp
              ports:
                - 22
              cidr_ip: 0.0.0.0/0
              rule_desc: allow all on ssh port
        register: result_sec_group

      - name: "Provision instance(s)"
        ec2:
          id: "{{ id }}"
          group_id: "{{ result_sec_group.group_id }}"
          image: "{{ image }}"
          instance_type: t2.micro
          region: "{{ region }}"
          wait: true
          exact_count: 1
          count_tag:
            Name: "sye_test_ansible"
          instance_tags:
            Name: "sye_test_ansible"
            to_post_provision: yes
        register: ec2_info

      - name: "debug instance popped"
        debug:
            msg: "instances_info: {{ ec2_info }}" 
      
      - name: "Make available vminfo for next jobs"
        set_stats:
          data:
            facts_to_gather:  "{{ ec2_info }}"

      tags: ['never', 'create_ec2']