---
- hosts: vm
  tasks:
    - name: Gather all registered virtual machines
      vmware_vm_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
      delegate_to: localhost
      register: vminfo

    - name: "Make available vminfo for next jobs"
      set_stats:
        data:
          facts_to_gather:  "{{ vminfo }}"
