---
# - name: Get instances facts
#   ec2_instance_info:
#     region: "{{ region }}"
#   register: result

- name: Create security group
  ec2_group:
    name: "{{ sec_group }}"
    description: "Sec group for app {{ id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on ssh port
  register: result_sec_group

- name: Create new key pair
  ec2_key:
    name: id_rsa
    region: "{{ region }}"
  register: ec2_key

- name: Save private key
  copy: content="{{ ec2_key.key.private_key }}" dest="../aws-private.pem" mode=0600
  when: ec2_key.changed

- name: Provision instance(s)
  ec2:
    key_name: "id_rsa"
    id: "{{ id }}"
    group_id: "{{ result_sec_group.group_id }}"
    image: "{{ image }}"
    instance_type: t2.micro
    region: "{{ region }}"
    wait: true
    exact_count: 1
    count_tag:
      Name: "sye_test_ansible"
    instance_tags:
      Name: "sye_test_ansible"
      to_post_provision: yes
  register: ec2_info

- name: debug instance popped
  debug:
      msg: "instances_info: {{ ec2_info.tagged_instances[0].public_ip }}" 

- name: Make available vminfo for next jobs
  set_stats:
    data:
      ec2_info:  "{{ ec2_info }}"